use { observable } from resources

variant error {
	error-with-description(string),
}

resource events {
	static get: function() -> events
	listen: function(ob: observable) -> events
	exec: function(duration: u64) -> unit
}
